# Generated by Django 3.0.3 on 2020-02-24 04:22
# Generated by Django 3.0.3 on 2020-02-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
    ]
