# Generated by Django 3.0.3 on 2020-02-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_movie_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
