# Generated by Django 3.0.3 on 2020-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20200303_0131'),
        ('film', '0002_auto_20200303_0322'),
    ]

    operations = [
    ]
