# Generated by Django 3.0.3 on 2020-03-03 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Movie'),
        ),
    ]
