# Generated by Django 3.0.3 on 2020-03-03 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Movie'),
        ),
        migrations.AddField(
            model_name='episode',
            name='next_episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='episode.Episode'),
        ),
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='episode.Episode'),
        ),
    ]
