# Generated by Django 3.0.3 on 2020-02-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
