# Generated by Django 3.0.3 on 2020-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_comment_user'),
        ('episode', '0002_auto_20200303_0131'),
    ]

    operations = [
    ]
